version: 2
jobs:
  build:
    working_directory: ~/react-native-gl-image-cropper
    docker:
      - image: circleci/node:10.11
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Install Example dependencies
          working_directory: ~/react-native-gl-image-cropper/example
          command: npm install
      - save_cache:
          key: v1-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
            - example/node_modules
      - run:
          name: Run lint
          command: npm run lint

workflows:
  version: 2
  build:
    jobs:
      - build
